### ISSUE TITLE
how to render only light-mode

### ISSUE THREAD

**Issue by gentleShark** [jooplaan/gatsby-london-night-and-day#1]
Thank you for creating this Gatsby starter. I've noticed depending on which browser I'm using, sometimes the light theme is rendered and sometimes the dark theme is rendered (though consistently the same in the different browsers). If I wanted only the light-mode to be rendered, is there a way to do that?

**Comment by gentleShark** [comment]
I figured it out. I achieved what I looking to do by changing the light-mode mixin in mixins.scss to:
@mixin light-mode {
  @content; 
}
Thanks!

**Comment by jooplaan** [comment]
@gentleShark, if you aim to have a design which is light only and no dark at all, you can also look at this:
https://github.com/ImedAdel/gatsby-london

**Comment by gentleShark** [comment]
thanks! Also, I noticed one minor problem where the bottom half of .site-head-container was cut off on the iPhone. The fix for that was just removing z-index: -1;
